#!/usr/bin/env python3
"""Convert an optional raw MS51 APROM binary into a small C translation unit."""

from __future__ import annotations

import argparse
import pathlib
import tempfile
import zlib


MAX_MS51_IMAGE_SIZE = 32 * 1024


def render_blob(data: bytes, source: str) -> str:
    crc = zlib.crc32(data) & 0xFFFFFFFF
    if data:
        rows = []
        for offset in range(0, len(data), 16):
            values = ", ".join(f"0x{byte:02X}" for byte in data[offset : offset + 16])
            rows.append(f"    {values},")
        body = "\n".join(rows)
        array_decl = f"const uint8_t g_ms51_firmware[] = {{\n{body}\n}};"
    else:
        # ISO C does not support zero-length arrays. The public size remains 0.
        array_decl = "const uint8_t g_ms51_firmware[1] = { 0xFF };"

    escaped_source = source.replace("\\", "\\\\").replace('"', '\\"')
    return f"""/* Auto-generated by tools/embed_ms51_firmware.py. Do not edit. */
#include <stddef.h>
#include <stdint.h>

{array_decl}
const size_t g_ms51_firmware_size = {len(data)}u;
const uint32_t g_ms51_firmware_crc32 = UINT32_C(0x{crc:08X});
const char g_ms51_firmware_source[] = "{escaped_source}";
"""


def write_if_changed(path: pathlib.Path, content: str) -> None:
    if path.exists() and path.read_text(encoding="utf-8") == content:
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    with tempfile.NamedTemporaryFile(
        "w", encoding="utf-8", newline="\n", dir=path.parent, delete=False
    ) as handle:
        handle.write(content)
        temporary = pathlib.Path(handle.name)
    temporary.replace(path)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--input", required=True, type=pathlib.Path)
    parser.add_argument("--output", required=True, type=pathlib.Path)
    args = parser.parse_args()

    if args.input.is_file():
        data = args.input.read_bytes()
        # Keep the ESP32 image reproducible across different checkout paths.
        source = "firmware/ms51_app.bin"
    else:
        data = b""
        source = "firmware/ms51_app.bin (not found)"

    if len(data) > MAX_MS51_IMAGE_SIZE:
        parser.error(
            f"{args.input} is {len(data)} bytes; MS51FC0AE APROM is at most "
            f"{MAX_MS51_IMAGE_SIZE} bytes"
        )

    write_if_changed(args.output, render_blob(data, source))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
